### ISSUE TITLE
export.sh missing?

### ISSUE THREAD

**Issue by viddypiddy** [swood/varna#2]
The README mentions an export.sh - which I cannot find in the repository.

So when running the script of course i get:
IOError: [Errno 2] No such file or directory: 'users_special.json'
Since this seemingly needs to be exported from this script.

**Comment by swood** [comment]
Hi, @viddypiddy.
I'm sorry, I forgot to add that file.
Now it is present in the repository, and you could use it to generate file user_special.json.
I also have updated varna.py with all my fixes.
Thank you for using my soft.

**Comment by viddypiddy** [comment]
Thank you!
