### ISSUE TITLE
crowd?

### ISSUE THREAD

**Issue by jby** [swood/varna#3]
It would seem that your script _requires_ a file containing users from crowd. Why? Not all HipChat-installs uses Crowd for it's users...

**Comment by swood** [comment]
Hi @jby.
I'm sorry to keep myself waiting.
Yes, wrote that script based on my original issue. But you can generate your additional file. 
In the next two days, I'll write the script which will be based on users.json (HipChat export file).

**Comment by jby** [comment]
Yeah, well - I went with https://github.com/ergon/migratemost instead.
However I came to this conclusion, regardless of migration script (and regardless of which LDAP-enabled chat system you want to import to): https://jby.github.io/Normalize-HC-usernames/
